[profile.default]
src = "contracts"   # point to your existing contracts folder
out = "out"         # optional, compiled artifacts go here
test = "tests/solidity"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = { version = "1.9.4" }
